"""Tests for Markdown export."""

from agentguard.builder import TraceBuilder
from agentguard.markdown import trace_to_markdown


class TestMarkdown:
    def test_basic(self):
        trace = (TraceBuilder("Test Pipeline")
            .agent("researcher", duration_ms=3000, token_count=1000, cost_usd=0.03)
                .tool("web_search", duration_ms=1000)
            .end()
            .handoff("researcher", "writer", context_size=500)
            .agent("writer", duration_ms=5000)
            .end()
            .build())

        md = trace_to_markdown(trace)
        assert "# ✅ Test Pipeline" in md
        assert "Score" in md
        assert "researcher" in md
        assert "Handoffs" in md

    def test_with_errors(self):
        trace = (TraceBuilder("Error Pipeline")
            .agent("bad", status="failed", error="API crashed")
            .end()
            .build())

        md = trace_to_markdown(trace)
        assert "❌" in md
        assert "API crashed" in md
        assert "Errors" in md

    def test_without_details(self):
        trace = (TraceBuilder("Simple")
            .agent("a").end()
            .build())
        md = trace_to_markdown(trace, include_details=False)
        assert "Summary" in md
        assert "Generated by AgentGuard" in md
