"""Diagnostics compatibility package for AgentGuard.

This package establishes the diagnostics import surface while the
underlying implementations still live in top-level modules.
"""

from agentguard.analysis import (  # noqa: F401
    BottleneckReport,
    ContextFlowPoint,
    ContextFlowReport,
    CostYieldEntry,
    CostYieldPathSummary,
    CostYieldReport,
    CounterfactualAnalysis,
    CounterfactualResult,
    DecisionAnalysis,
    DecisionRecord,
    DurationAnomaly,
    DurationAnomalyReport,
    FailureAnalysis,
    FailureNode,
    FlowAnalysis,
    HandoffInfo,
    RepeatedBadDecision,
    WorkflowPattern,
    WorkflowPatternAnalysis,
    analyze_bottleneck,
    analyze_context_flow,
    analyze_cost,
    analyze_cost_yield,
    analyze_counterfactual,
    analyze_decisions,
    analyze_failures,
    analyze_flow,
    analyze_retries,
    analyze_timing,
    analyze_workflow_patterns,
    detect_duration_anomalies,
    detect_repeated_bad_decisions,
)
from agentguard.context_flow import (  # noqa: F401
    ContextBandwidth,
    ContextFlowAnalysis,
    ContextSnapshot,
    ContextTransition,
    analyze_context_flow_deep,
)
from agentguard.correlation import (  # noqa: F401
    CorrelatedEvent,
    CorrelationReport,
    SpanFingerprint,
    analyze_correlations,
    correlate_failures_to_handoffs,
    detect_patterns,
    fingerprint_span,
)
from agentguard.flowgraph import (  # noqa: F401
    ExecutionPhase,
    FlowGraph,
    FlowNode,
    build_flow_graph,
)
from agentguard.propagation import (  # noqa: F401
    CausalLink,
    CausalChain,
    PropagationAnalysis,
    analyze_handoff_chains,
    analyze_propagation,
    compute_context_integrity,
    hypothetical_failure,
)
from agentguard.scoring import ScoreComponent, TraceScore, score_trace  # noqa: F401
from agentguard.timeline import EventType, Timeline, TimelineEvent, build_timeline  # noqa: F401
from agentguard.tree import (  # noqa: F401
    TreeStats,
    compute_tree_stats,
    detect_cycles,
    find_orphans,
    find_roots,
    tree_to_text,
)

__all__ = [
    "BottleneckReport",
    "CausalChain",
    "CausalLink",
    "ContextBandwidth",
    "ContextFlowAnalysis",
    "ContextFlowPoint",
    "ContextFlowReport",
    "ContextSnapshot",
    "ContextTransition",
    "CorrelatedEvent",
    "CorrelationReport",
    "CostYieldEntry",
    "CostYieldPathSummary",
    "CostYieldReport",
    "CounterfactualAnalysis",
    "CounterfactualResult",
    "DecisionAnalysis",
    "DecisionRecord",
    "DurationAnomaly",
    "DurationAnomalyReport",
    "EventType",
    "ExecutionPhase",
    "FailureAnalysis",
    "FailureNode",
    "FlowAnalysis",
    "FlowGraph",
    "FlowNode",
    "HandoffInfo",
    "PropagationAnalysis",
    "RepeatedBadDecision",
    "ScoreComponent",
    "SpanFingerprint",
    "Timeline",
    "TimelineEvent",
    "TraceScore",
    "TreeStats",
    "WorkflowPattern",
    "WorkflowPatternAnalysis",
    "analyze_bottleneck",
    "analyze_context_flow",
    "analyze_context_flow_deep",
    "analyze_correlations",
    "analyze_cost",
    "analyze_cost_yield",
    "analyze_counterfactual",
    "analyze_decisions",
    "analyze_failures",
    "analyze_flow",
    "analyze_handoff_chains",
    "analyze_propagation",
    "analyze_retries",
    "analyze_timing",
    "analyze_workflow_patterns",
    "build_flow_graph",
    "build_timeline",
    "compute_context_integrity",
    "compute_tree_stats",
    "correlate_failures_to_handoffs",
    "detect_cycles",
    "detect_duration_anomalies",
    "detect_patterns",
    "detect_repeated_bad_decisions",
    "find_orphans",
    "find_roots",
    "fingerprint_span",
    "hypothetical_failure",
    "score_trace",
    "tree_to_text",
]