"""Trace to Markdown — generate documentation-friendly trace reports.

Export traces as Markdown documents for:
- Pull request descriptions
- Documentation
- Sharing in chat/wikis
"""

from __future__ import annotations

from agentguard.core.trace import ExecutionTrace, SpanStatus, SpanType
from agentguard.metrics import extract_metrics
from agentguard.scoring import score_trace
from agentguard.tree import tree_to_text


def trace_to_markdown(trace: ExecutionTrace, include_details: bool = True) -> str:
    """Generate a Markdown report for a trace."""
    score = score_trace(trace)
    m = extract_metrics(trace)

    status_icon = "✅" if trace.status == SpanStatus.COMPLETED else "❌"

    lines = [
        f"# {status_icon} {trace.task or 'Trace Report'}",
        "",
        f"**Score:** {score.overall:.0f}/100 ({score.grade}) | "
        f"**Status:** {trace.status.value} | "
        f"**Duration:** {trace.duration_ms:.0f}ms" if trace.duration_ms else "",
        "",
        "## Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Spans | {m.span_count} |",
        f"| Agents | {m.agent_count} |",
        f"| Tools | {m.tool_count} |",
        f"| Handoffs | {m.handoff_count} |",
        f"| Tokens | {m.total_tokens:,} |",
        f"| Cost | ${m.total_cost_usd:.4f} |",
        f"| Success Rate | {m.success_rate:.0%} |",
        "",
    ]

    # Score breakdown
    lines.append("## Quality Score")
    lines.append("")
    for c in score.components:
        bar = "█" * int(c.score / 10) + "░" * (10 - int(c.score / 10))
        lines.append(f"- **{c.name}** {bar} {c.score:.0f}/100")
    lines.append("")

    # Span tree
    lines.append("## Execution Tree")
    lines.append("")
    lines.append("```")
    lines.append(tree_to_text(trace))
    lines.append("```")
    lines.append("")

    if include_details:
        # Errors
        errors = [s for s in trace.spans if s.status == SpanStatus.FAILED and s.error]
        if errors:
            lines.append("## Errors")
            lines.append("")
            for s in errors:
                lines.append(f"- **{s.name}**: {s.error}")
            lines.append("")

        # Handoffs
        handoffs = [s for s in trace.spans if s.span_type == SpanType.HANDOFF]
        if handoffs:
            lines.append("## Handoffs")
            lines.append("")
            for h in handoffs:
                ctx_size = f"{h.context_size_bytes:,}B" if h.context_size_bytes else "?"
                lines.append(f"- {h.handoff_from} → {h.handoff_to} ({ctx_size})")
            lines.append("")

    lines.append(f"---\n*Generated by AgentGuard · Trace ID: {trace.trace_id}*")

    return "\n".join(lines)
